### ISSUE TITLE
Turning off emails doesn't actually unsubscribe a user

### ISSUE THREAD

**Issue by bwighthunter** [doconix/island#2]
The UI for turning off email notifications is there, but it doesn't seem to be doing anything, because I still receive emails for every post in every forum.

I will look into the code myself, and try and resolve it.

**Comment by doconix** [comment]
The query that filters this is in thread.py, line 155.  I'll look into it as well.

**Comment by doconix** [comment]
I just checked this, and it seems to be working right.  I'm going to close it for now.  Email me directly (ca at byu) if you are still having issues.  I can look into it with you.

**Comment by doconix** [comment]
I just rewrote the query that determines which users to send email to.  I think this new one will work better.
